# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3b37fa51e3d04233c8d4a810ae3335e5922c9567a62ba567f8fa98400cb2f8e2fe756ed6737d6cea28c8ca39b3f2de700af8bfb35a66a06885f359052c7a23

test:
  secret_key_base: 30c027e36a2981b1aa80de92064e4f08618489f1d2d5bafdcb92ad93ff1565c56f454defda7a806edd31ab37c53a3687374157f68de601915a9a88798d85e6f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
